### PR TITLE
Add missing import in backends

### PR DESCRIPTION
**Pull request by conradoqg**

### CODE REVIEW

**Comment by freman** [comment]
Not sure how no-one noticed that before now (I don't personally use it, which is ironic when I started this it was one of the options we were investigating)

**Comment by conradoqg** [comment]
Probably nobody uses it. Anyway, the LDAP itself is working. How long do you think it takes before it is available in the official caddy plugin? Do you need to publish it or once in the master it's already published?

**Comment by freman** [comment]
yes I do, thanks for reminding me.

edit:
Something is borked, I'll have to take a look in the morning.

```
ok  	github.com/freman/caddy-reauth	1.037s
?   	github.com/freman/caddy-reauth/backend	[no test files]
?   	github.com/freman/caddy-reauth/backends	[no test files]
--- FAIL: TestAuthenticateSimple (0.40s)
```

**Comment by conradoqg** [comment]
Thanks man

**Pull request merged**
